language: ruby
rvm:
  - 1.9.3
before_script:
  - "cp config/log4r.yml.sample config/log4r.yml"
  - "cp config/log4r_fixity_check.yml.sample config/log4r_fixity_check.yml"
  - "cp config/database.yml.sample config/database.yml"
  - "rake jetty:clean"
  - "rake jetty:config"
script: "rake dul_hydra:ci"
branches:
  only:
    - travis-ci
