log4r_config:
    loggers:
        - name      : batch
          level     : INFO
          trace     : 'false'
          outputters:
            - file_batch
    outputters:
        - type      : StdoutOutputter
          name      : stdout
          formatter :
            date_pattern: '%F %T'
            pattern     : '%d %l: %m '
            type        : PatternFormatter
        - type      : FileOutputter
          name      : file_batch
          filename  : "#{filename}"
          formatter :
            date_pattern: '%F %T'
            pattern     : '%d %l: %m '
            type        : PatternFormatter

    
