log4r_config:
    loggers:
        - name      : preparation
          level     : INFO
          trace     : 'false'
          outputters:
            - file_preparation
        - name      : ingest
          level     : INFO
          trace     : 'false'
          outputters:
            - file_ingest
        - name      : postprocess
          level     : INFO
          trace     : 'false'
          outputters:
            - file_postprocess
    outputters:
        - type      : StdoutOutputter
          name      : stdout
          formatter :
            date_pattern: '%F %T'
            pattern     : '%d %l: %m '
            type        : PatternFormatter
        - type      : FileOutputter
          name      : file_preparation
          filename  : "#{basepath}log/ingest_preparation.log"
          formatter :
            date_pattern: '%F %T'
            pattern     : '%d %l: %m '
            type        : PatternFormatter
        - type      : FileOutputter
          name      : file_ingest
          filename  : "#{basepath}log/batch_ingest.log"
          formatter :
            date_pattern: '%F %T'
            pattern     : '%d %l: %m '
            type        : PatternFormatter
        - type      : FileOutputter
          name      : file_postprocess
          filename  : "#{basepath}log/ingest_postprocess.log"
          formatter :
            date_pattern: '%F %T'
            pattern     : '%d %l: %m '
            type        : PatternFormatter

    
